engines:
   rubocop:
     enabled: true
   eslint:
     enabled: true
   scss-lint:
     enabled: true
   bundler-audit:
     enabled: true
   watson:
     enabled: true

ratings:
    paths:
    - "app/**/*"
    - "lib/**/*"
    - "**/*.rb"
    - "frontend/**/*.js"
    - "app/assets/**/*.scss"

exclude_paths:
- "spec/**/*"
- "vendor/**/*"
