language: ruby

cache:
  directories:
    - vendor/bundle
    - app/frontend/node_modules

rvm: 2.1.3

addons:
  postgresql: 9.3

sudo: false

before_install:
  - "npm config set spin false"
  - "travis_retry npm install -g npm@^2"

install:
  - bundle install --deployment --jobs=3 --retry=3
  - travis_retry npm install -g bower
  - (cd app/frontend; travis_retry npm install)
  - (cd app/frontend; travis_retry bower install)

before_script:
  - bundle exec rake db:create db:structure:load

script:
  - bundle exec rake test:all
  - (cd app/frontend; npm test)

#after_success:
#  - 'echo -e "Host 107.170.189.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
#  - ssh root@107.170.189.56 "/var/hummingbird/deploy.sh"

notifications:
  hipchat:
    rooms:
      secure: aXpt7vF8j08UA48UltX9BOd5PjaSp8EG6lcKtjM6oi2K0EF+NlJq3RZRKgrYbNTISbOjJUJlFdbGG8oUBi0ilZV0kvF2JYlB16HZgUEcsSeTInUEmPZoy+VvgTve/L+b4+2cgC0pyxC6kzCk9PAYQ3ZCsqSbwISZmHV4cG1k9tg=
    template:
      - 'Build #%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
