language: ruby
rvm:
  - 2.2.3

sudo: false

addons:
  postgresql: 9.4

cache:
  directories:
    - server/vendor/bundle
    - client/node_modules

before_install:
  - mkdir -p travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - nvm install 0.12
  - npm config set spin false

install:
  - (cd server; bundle install --deployment --jobs=3 --retry=3)
  - (travis_retry npm install -g bower)
  - (cd client; travis_retry npm install)
  - (cd client; travis_retry bower install)

before_script:
  - (cd server; bundle exec rake db:create db:schema:load)

script:
  - (cd server; bundle exec rspec)
  - (cd client; ember test)

notifications:
  slack:
    secure: mWUt5kViIa34qIR3BcQwUmTZ/1+eqv3WSk4ZRdOFDqidn8kFtmhAb/xgXknuqQc0i/eS427bbxvREogmInXyKgvuMzj1WONcZv2lA/rvEm2/gMJ6x2YnDCUHtuQnLrPpcESKRmC396qPf+Uuw76A6q33TyWxmc7aRP1hG2J14+Y=
