language: ruby

sudo: false

# Postgres v9.4 and ElasticSearch vWhoGivesAFuck
addons:
  postgresql: 9.4
services:
  - elasticsearch

cache:
  directories:
    - server/vendor/bundle
    - client/node_modules
    - client/bower_components

env:
  global:
    - USE_NODE=5.9
    - USE_RUBY=2.3.1
  matrix:
    - TESTGROUP=client
    - TESTGROUP=server

before_install:
  - source scripts/travis/before_install

install:
  - source scripts/travis/install

before_script:
  - source scripts/travis/before_script

script:
  - scripts/test

notifications:
  slack:
    secure: RnK+D0LqaCtzGGfpHjZU302v7q03y7SOgt2JM84jqbHt9n+hW1cEjB1AiPAS0c8zl/fftm2ZXL8AZ1fZcGvfRtEkEGxNvUtdtOHJ/cbm3slvKBV6W5fjNTvK35xL+ryQvtABRpMId0u5b8kn6DB6KaNBA8CQ9JeblrxJJjAYjUQ=
