language: ruby

sudo: false

addons:
  postgresql: 9.4

cache:
  directories:
    - server/vendor/bundle
    - client/node_modules
    - client/bower_components
    - travis-phantomjs

env:
  global:
    - USE_NODE=0.12
  matrix:
    - TESTGROUP=client
    - TESTGROUP=server USE_RUBY=ruby-2.2.3
    - TESTGROUP=server USE_RUBY=rbx-2.8

before_install:
  - source bin/travis/before_install

install:
  - source bin/travis/install

before_script:
  - source bin/travis/before_script

script:
  - bin/test

notifications:
  slack:
    secure: mWUt5kViIa34qIR3BcQwUmTZ/1+eqv3WSk4ZRdOFDqidn8kFtmhAb/xgXknuqQc0i/eS427bbxvREogmInXyKgvuMzj1WONcZv2lA/rvEm2/gMJ6x2YnDCUHtuQnLrPpcESKRmC396qPf+Uuw76A6q33TyWxmc7aRP1hG2J14+Y=
