language: ruby

cache:
  directories:
    - vendor/bundle
    - frontend/node_modules

rvm: 2.1.3

addons:
  postgresql: 9.3

sudo: false

before_install:
  - "npm config set spin false"
  - "travis_retry npm install -g npm@^2"

install:
  - bundle install --deployment --jobs=3 --retry=3
  - travis_retry npm install -g bower
  - (cd frontend; travis_retry npm install)
  - (cd frontend; travis_retry bower install)

before_script:
  - bundle exec rake db:create db:structure:load

script:
  - bundle exec rake test:all
  - (cd frontend; npm test)

#after_success:
#  - 'echo -e "Host 107.170.189.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
#  - ssh root@107.170.189.56 "/var/hummingbird/deploy.sh"

notifications:
  slack:
    secure: mWUt5kViIa34qIR3BcQwUmTZ/1+eqv3WSk4ZRdOFDqidn8kFtmhAb/xgXknuqQc0i/eS427bbxvREogmInXyKgvuMzj1WONcZv2lA/rvEm2/gMJ6x2YnDCUHtuQnLrPpcESKRmC396qPf+Uuw76A6q33TyWxmc7aRP1hG2J14+Y=
