 version: '2'
 services:
  # Database servers
  postgres:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
  redis:
    image: redis
  elasticsearch:
    image: elasticsearch

  # Web server, routing /api and / to server, client respectively
  nginx:
    build:
      context: ./scripts
      dockerfile: Dockerfile.nginx
    links: [client, server]
    ports: [80]

  # Rails server
  server: &rails
    links: [postgres, redis, elasticsearch]
    build: ./server
    volumes:
      - ./server:/opt/hummingbird/server
    environment:
      RAILS_ENV: development

  # Sidekiq
  sidekiq:
    <<: *rails
    command: [sidekiq]

  # Ember server
  client:
    build: ./client
    volumes:
      - ./client:/opt/hummingbird/client
      - /opt/hummingbird/client/node_modules
    environment:
      EMBER_ENV: development
    ports:
      - "57777:57777"
