version: '2'

volumes:
  postgres:
    driver: local
  node_modules:
    driver: local

services:
  # Database servers
  postgres:
    image: postgres:9.3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
  elasticsearch:
    image: elasticsearch

  # Web server, routing /api and / to server, client respectively
  nginx:
    build:
      context: ./scripts
      dockerfile: Dockerfile.nginx
    links: [client, server]
    ports: [80]

  # Rails server
  server: &rails
    links: [postgres, redis, elasticsearch]
    build: ./server
    volumes:
      - ./server:/opt/hummingbird/server
    environment:
      DATABASE_URL: 'postgresql://postgres:mysecretpassword@postgres/'
      REDIS_URL: 'redis://redis/1'
      RAILS_ENV: development

  # Sidekiq
  sidekiq:
    <<: *rails
    command: [sidekiq]

  # Ember server
  client:
    build: ./client
    volumes:
      - ./client:/opt/hummingbird/client
      - /opt/hummingbird/client/node_modules
      - /opt/hummingbird/client/bower_components
    tmpfs:
      - /opt/coachnite/client/tmp
    environment:
      EMBER_ENV: development
    ports: ['57777:57777']
