test:
  adapter: postgresql
  database: hummingbird_test
  host: localhost
  
production:
  adapter: postgresql
  database: hummingbird_production
  username: hummingbird
  password: <%= ENV['POSTGRES_PASS'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
  pool: 50

development:
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  username: <%= ENV['POSTGRES_ENV_POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
  database: postgres
