development:
  adapter: postgresql
  database: <%= ENV['POSTGRES_DATABASE'] ||= "hummingbird_development" %>
  host: <%= ENV['POSTGRES_HOST'] ||= "localhost" %>
  port: <%= ENV['POSTGRES_PORT'] ||= "5432" %>
  username: <%= ENV['POSTGRES_USERNAME'] ||= "" %>
  password: <%= ENV['POSTGRES_PASSWORD'] ||= "" %>

test:
  adapter: postgresql
  database: hummingbird_test
  host: localhost
  
production:
  adapter: postgresql
  database: hummingbird_production
  username: hummingbird
  password: <%= ENV['POSTGRES_PASS'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
  pool: 50
  database: postgres
